name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches: [main]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          sudo rm -rf node_modules
          npm install
          npm test -- --group=bcn

  
  JestUbuntu:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          sudo rm -rf node_modules
          npm install
          npm test -- --group=azure
